### PR TITLE
Build tools for DART that do not need mkmf_ and path_names_ files 

### LINKED ISSUE #114: reduce repetition in path_names files
To think about:

Is it possible to reduce the repetition in path_names_ files?

For example, using  mkmf to search directories rather than individual files. 

It seems prone to error to change (for example) 91 path_names files when a new file is required for preprocess. 

At least for preprocess, and other programs that the path names don't change between models, it seems like we could have one path_names_preprocess. 

````
../../../build_templates/mkmf -v -p preprocess -t ../../../build_templates/mkmf.template   \   
 -a "../../.." path_names_preprocess 
````

becomes
````
../../../build_templates/mkmf -v -p preprocess -t ../../../build_templates/mkmf.template   \   
 -a "../../.." HELLO_ONE_LOCATION/path_names_preprocess 

````

### LINKED ISSUE #129: utilities oned and threed_sphere do not have work directories
DART/observations/utilities/oned
DART/observations/utilities/threed_sphere

do not have work directories, but do have quickbuild.csh scripts

### LINKED ISSUE #141: compiling multiple models/ multiple converters at once with local obs_kind_mod and obs_def_mod
Back burner issue: 

At the moment, 
````
obs_kind_mod.f90 
obs_def_mod.f90
````

are created in 
````
assimilation_code/modules/observations/
observations/forward_operators/
````

Having local obs_kind_mod.f90 and obs_def_mod.f90 created in the work directory would let you compile multiple models/multiple converters at once. 

Is this important for users?  No not really. Maybe for debugging coupled models if the different models have different obs_def files and/or different quantity files. 

It would let you run all quickbuild.csh scripts simultaneously which would speed up testing. 
Note you could find&replace in path_names and input_nml to run quickbuild.csh simultaneously for testing.

### LINKED ISSUE #157: potential duplicate obs_assim_count.f90
We have the following two files:

- assimilation_code/programs/obs_assim_count/obs_assim_count.f90
- assimilation_code/programs/obs_utils/obs_assim_count.f90

Are they identical, can be consolidated?   Not looked into it at all ...

### LINKED ISSUE #216: Feature request: make it easier to refactor the DART code
### Use case  

new code is mostly added to existing modules instead of being broken out into smaller modules.  existing modules grow larger and more difficult to maintain as the years go by.  it can also complicate the dependencies between modules since fortran doesn't allow circular references in modules.

### Is your feature request related to a problem?  

as developers add new routines to the system, 90% of the time they add them to existing modules instead of breaking out closely related functions into smaller separate modules.  this is because to move routines between files requires updating 100+ path_names files in the system which is onerous, and then updating the use lines in all the source code which is doubly onerous.  (there are no good tools for constructing the use lines automatically, so many files already contain use routines which aren't actually needed because they are copied from another file to start.)  maybe more importantly, this also breaks functionality for any user executables where their path_names and source files aren't in the public repo so we can't update them.

### Describe the your preferred solution  

if i get hit by a bus, here's as far as i've thought it through.

- every module EXCEPT the locations mod, the mpi-related mods (mpi_utils, win_mod) and the model_mod should be built and archived (ar) into a library, libDART.a and/or libDART.so
- user code should: use dart_lib_mod, only:  xxx, xxx, xxx
- a single dart_lib_mod can "use" all the source mods and only that one file should need to change if a new module is added or routines are moved between modules.  there would be no code in this module, just a series of use lines for the entire set of public routines
- path_names files only contain the appropriate locations mod (oned, threed_sphere, etc), mpi or non-mpi mods, and the model_mod plus any additional modules needed by the model_mod.
- mkmf should make executables dependent on libDART.  it might take a new option, or that functionality may already be there.  the make rule for libDART could be to cd to the DART/lib directory and build the library there with a static makefile.  then quickbuild and mkmf_xxx work the same as before.  if libDART is up-to-date it is just linked with the program; if not it is built the first time.
- the linker flags can use " -L $DART/lib -lDART "  (that's dash ell DART) and that takes care of linking in the library whether it is built static (.a) or dynamic (.so)
- OR, the library could be listed just like source files in the path_names file.  that would allow different versions of the dart library to be used by changing the path_names file.  i don't know if mkmf knows what to do if a file in the path_names is a library.  it might work already, or we might have to add additional capability to mkmf to go build the library (cd into the library directory; make libname) if it doesn't yet exist.

### Describe any alternatives you have considered  

i haven't thought of another good way to package this so changes in where the source code lives is transparent.  it is sorely needed.  the utilities module is too large; the filter_assim module needs refactoring and some routines moved out; the obs_sequence module contains routines which don't need access to any of the internal data structures and could be moved out.  (obs_sequence also has some obs_def code in it which i think could be separated if the module was broken into smaller pieces, but i'm not 100% sure about this.) since we encourage the fortran "use only ... " syntax moving routines means not only changing path_names files, which could possibly be automated, but also editing all source files which is a much trickier and painful change.

### LINKED ISSUE #327: run test logs do not capture error, only std out
The developer_test for the location_mod have std err to the screen and only std out to the log files.  I've not had a look at the other "developer_tests", but having a quick look there is mostly > and >>.

Running `threed_cartesian` just for brevity  here;
`./run_tests.csh`  vs. `cat buildlog.threed_cartesian.out `

hkershaw@cheyenne4:/glade/scratch/hkershaw/DART/pull_requests/pull_285/developer_tests/location(updt_bcs)$ ./run_tests.csh 

```
==================================================================
Start of location module tests at Mon Feb 7 10:46:11 MST 2022
==================================================================


build and run logs are in: /glade/scratch/hkershaw/DART/pull_requests/pull_285/developer_tests/location/testing_logs


------------------------------------------------------------------
Starting tests of location module threed_cartesian at Mon Feb 7 10:46:11 MST 2022
------------------------------------------------------------------


.............../../../../assimilation_code/location/threed_cartesian/location_mod.f90(19): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [OBS_KIND_MOD]
use         obs_kind_mod, only : get_num_types_of_obs, get_name_for_type_of_obs, get_index_for_type_of_obs
------------^
../../../../assimilation_code/location/threed_cartesian/location_mod.f90(19): error #6580: Name in only-list does not exist or is not accessible.   [GET_NUM_TYPES_OF_OBS]
use         obs_kind_mod, only : get_num_types_of_obs, get_name_for_type_of_obs, get_index_for_type_of_obs
---------------------------------^
../../../../assimilation_code/location/threed_cartesian/location_mod.f90(19): error #6580: Name in only-list does not exist or is not accessible.   [GET_NAME_FOR_TYPE_OF_OBS]
use         obs_kind_mod, only : get_num_types_of_obs, get_name_for_type_of_obs, get_index_for_type_of_obs
-------------------------------------------------------^
../../../../assimilation_code/location/threed_cartesian/location_mod.f90(19): error #6580: Name in only-list does not exist or is not accessible.   [GET_INDEX_FOR_TYPE_OF_OBS]
use         obs_kind_mod, only : get_num_types_of_obs, get_name_for_type_of_obs, get_index_for_type_of_obs
---------------------------------------------------------------------------------^
../../../../assimilation_code/location/threed_cartesian/location_mod.f90(895): error #6404: This name does not have a type, and must have an explicit type.   [GET_NUM_TYPES_OF_OBS]
typecount = get_num_types_of_obs()
------------^
compilation aborted for ../../../../assimilation_code/location/threed_cartesian/location_mod.f90 (code 1)
make: *** [location_mod.o] Error 1


ERROR - unsuccessful build of location module threed_cartesian at Mon Feb 7 10:46:12 MST 2022


==================================================================
End of location module tests at Mon Feb 7 10:46:12 MST 2022
==================================================================

```

hkershaw@cheyenne4:/glade/scratch/hkershaw/DART/pull_requests/pull_285/developer_tests/location(updt_bcs)$ cat /glade/scratch/hkershaw/DART/pull_requests/pull_285/developer_tests/location/testing_logs/buildlog.threed_cartesian.out 

```
 Makefile is ready.
ifort -O -assume buffered_io -fp-model precise -I/glade/u/apps/ch/opt/netcdf/4.8.1/intel/19.1.1//include  -c	../../../../assimilation_code/location/threed_cartesian/location_mod.f90
Makefile:24: recipe for target 'location_mod.o' failed
```

I'm not sure how much to care about this, but new tests should capture std err in the logs.

### LINKED ISSUE #333: bug: simple2.cdl in developer_tests/io/work causes ncgen to bomb
### Describe the bug

1. List the steps someone needs to take to reproduce the bug.  

```
cd developer_tests/io/work
./quickbuild.csh
```

If you have run `./quickbuild.csh` once already you will need to do `rm *.nc`

Or you can do
```
ncgen -o simple2.nc simple2.cdl
assertion failure: islistconst(con)

Abort trap: 6
```

### Error Message  

```
constructing io test data file 3 named simple2.nc
assertion failure: islistconst(con)

Abort
```

### Version of DART      
Which version of DART are you using? 
v9.13.2

### Have you modified the DART code?   
No  

### Build information
ncgen

### LINKED ISSUE #335: bug: obs_seq_to_netcdf for radiance obs is not built correctly when running quickbuild.csh
:bug: :bug: :whale:

### Describe the bug

1. List the steps someone needs to take to reproduce the bug.  

```
cd DART/models/wrf
./quickbuild.csh
```

3. What was the expected outcome?
obs_seq_to_netcdf for radiance built
obs_seq_to_netcdf built

5. What actually happened?  

radiance_obs_seq_to_netcdf gets built with the non-radiance obs_seq_to_netcdf code 
Both of these are program obs_seq_to_netcdf so if you run quickbuild.csh,  obs_seq_to_netcdf.o is built for the first program in the list, and radiance_obs/obs_seq_to_netcdf.f90 is never compiled.

### Error Message
You can see this if you don't have the RTTOV libraries in your mkmf.template  
`./quickbuild.csh`  (runs successfully but should fail for radiance_obs_seq_to_netcdf)

```
csh mkmf_radiance_obs_to_netcdf  
make
```

gives

```
../../../assimilation_code/programs/obs_seq_to_netcdf/radiance_obs/obs_seq_to_netcdf.f90(35): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [OBS_DEF_RTTOV_MOD]
use obs_def_rttov_mod, only : get_channel
----^
../../../assimilation_code/programs/obs_seq_to_netcdf/radiance_obs/obs_seq_to_netcdf.f90(506): error #6404: This name does not have a type, and must have an explicit type.   [GET_CHANNEL]
         my_channel  = get_channel(flavor,obs_key)
-----------------------^
../../../assimilation_code/programs/obs_seq_to_netcdf/radiance_obs/obs_seq_to_netcdf.f90(35): error #6580: Name in only-list does not exist or is not accessible.   [GET_CHANNEL]
use obs_def_rttov_mod, only : get_channel
------------------------------^
compilation aborted for ../../../assimilation_code/programs/obs_seq_to_netcdf/radiance_obs/obs_seq_to_netcdf.f90 (code 1)
make: *** [obs_seq_to_netcdf.o] Error 1
``` 

with ../../../observations/forward_operators/obs_def_mod.f90 in preprocess_nml:

```
../../../observations/forward_operators/obs_def_mod.f90(3340): error #5102: Cannot open include file 'rttov_direct.interface'
include "rttov_direct.interface"
--------^
../../../observations/forward_operators/obs_def_mod.f90(3341): error #5102: Cannot open include file 'rttov_read_coefs.interface'
include "rttov_read_coefs.interface"
```

### Which model(s) are you working with?
WRF

### Version of DART      
Which version of DART are you using? 
v9.13.2
been in the repo since  March 2020

### Have you modified the DART code?   
No

### Build information
Please describe:  
 1. mac
 2. intel
 but applies to any machine/build combo.

### PR DESCRIPTION
**Pull request by hkershaw-brown**
## Description:

There are science changes to DART in the pipeline that are potentially disruptive changes. However, a large part of the disruption is due to the build system in DART. For example, if you wanted to split filter_assim into two files, you would have to change ~730 path_names files.  

The goal is have a build system that lets dart developers refactor code without the tax of altering individual mkmf_ and path_names files.  And, ideally, as transparent as possible for DART users. 
 
Slides about the build system are  [here](https://docs.google.com/presentation/d/1SeT16gUN9bwfB2MVvHfMfjVPOpiv7Fp1jmrgkFVU3Zg/edit#slide=id.g11e70c7fb6a_0_135)
Original spec is [here](https://www.google.com/url?q=https://docs.google.com/document/d/1KPYJ6mNGT2uYid-tjHeGZ4Vq7PBN9nJ7gzKTDD2s7QY/edit?usp%3Dsharing&sa=D&source=calendar&ust=1652286978850245&usg=AOvVaw3-z01o0BmN6K_4Ge7AyqjY)

Changes for users:

1.  `./quickbuild.sh ` rather than  `./quickbuild.csh`
2. To build a single program  `./quickbuild.sh filter` rather than 

    ```
    ./preprocess
    csh mkmf_filter -mpi
    make
    ```

    Note you can still iterate over changing code and compiling using make
    ```
    ./quickbuild.sh filter
    *edit the code*
    make
    *edit the code*
    make
    ```

3. .f90 files in the work directory take precedence over .f90 files with the same name elsewhere. So you can 
     have a local version of `filter_assim_mod.f90` in work that will be used _instead_ of 
     `assimilation_code/modules/assimilation/assim_tools_mod.f90`

4. `quickdbuild.sh help` gives the quickdbuild.sh usage.

For developers,  added documentation in guide/quickbuild.rst about build functions and where these functions search for
source code. Html is [here](https://dart-documentation--348.org.readthedocs.build/en/348/guide/quickbuild.html)

### Fixes issues

Fixes #216,  fixes #335, fixes #333, fixes #157, fixes #129, fixes #327, fixes #114
`developer_tests/time_manager` now compiles.
Fixes #141 `developer_tests/build_everything` uses local obs_def/kind_mod.f90.

Renames obs_diag for streamflow to stream_flow_obs_diag. Note this does not fix issue #334.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

This pull request removes 1465 files  ~30% of the repo

### Documentation changes needed?

- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly. 
  - [x] I have updated the DART tutorial pdfs. 

### Tests
Please describe any tests you ran to verify your changes.
* Built DART executables (models, converters, developer tests) mac and Cheyenne

Note I've changed the code in `models/wrf_hydro/hydro_dart_py/hydrodartpy/core/dartclasses.py` to use `quickdbuild.sh`. However dartclasses.py expecting to `ls` the mkmf_ files to get a list of executables.   I'm not sure where the list of executables is used so this pull request may break hydro_dart_py.

## Checklist for merging

- [ ] Updated changelog entry
- [ ] Documentation updated
- [ ] Version tag 

## Testing Datasets

- [x] Dataset needed for testing available upon request
- [ ] Dataset download instructions included
- [ ] No dataset needed

### CODE REVIEW

**Review by nancycollins — APPROVED** [review]
i will confess to not reviewing all 1829 changed files individually.  i did run tests and everything worked as expected.  i think this is a positive step in lowering the barrier to making needed software changes and i approve this pull request.

not for this pull request, but in the future we should stop adding extensions to commands (e.g. quickbuild instead of quickbuild.csh or quickbuild.sh or quickbuild.py).   then we can change the implementation language from csh to sh to python to a compiled program and it will all be transparent to the end user (and other scripts).  commands should never have had .csh extensions.  apparently it made it easier to have svn automatically set the permissions to add the executable flags.  in my opinion that wasn't a good choice.  it's too late for our existing scripts, but for future scripts it would be a better practice to drop the file extension altogether.  (end rant)

**Comment by hkershaw-brown** [comment]
I love a good Nancy rant.
Thanks for looking at Nancy.  I promise not to do any more 1829 file pull
requests.  (Probably this is a lie)

**Comment by nancycollins** [comment]
just a warning that with the new build system, i found that 
 models/wrf/experiments/Radar/IC/sounding_perturbation/pert_sounding_module.f90 
does not compile with gfortran v11.2.0 on my mac.  there are 3 places with an integer/real mismatch in subroutine arguments.  this isn't our code - i'm guessing from the directory and name that it's used to perturb synthetic radar obs for testing/experiments.  there are probably no makefiles that use this module but the new build system tries to compile everything and fails the wrf build because of this.  i took a quick stab at trying to see if i could resolve the real(4) vs integer(4) mismatch but it wasn't simple to see what could be changed without breaking the code.

**Comment by hkershaw-brown** [comment]
> just a warning that with the new build system, i found that models/wrf/experiments/Radar/IC/sounding_perturbation/pert_sounding_module.f90 does not compile with gfortran v11.2.0 on my mac. there are 3 places with an integer/real mismatch in subroutine arguments. this isn't our code - i'm guessing from the directory and name that it's used to perturb synthetic radar obs for testing/experiments. there are probably no makefiles that use this module but the new build system tries to compile everything and fails the wrf build because of this. i took a quick stab at trying to see if i could resolve the real(4) vs integer(4) mismatch but it wasn't simple to see what could be changed without breaking the code.

There is a script to compile this code:
`DART/models/wrf/experiments/Radar/IC/sounding_perturbation/compile_pert_sounding.csh `. It does not compile on main with gnu/11.2.0

```
hkershaw@cheyenne5:/glade/scratch/hkershaw/DART/Bugs/mismatch/DART/models/wrf/experiments/Radar/IC/sounding_perturbation(main)$ gfortran -c pert_sounding_module.f90 
pert_sounding_module.f90:175:27:

  175 |       amp(m) = mag*gaussdev(iseed1)
      |                           1
Error: Type mismatch in argument ‘idum’ at (1); passed REAL(4) to INTEGER(4)
pert_sounding_module.f90:179:34:

  179 |          phs(m) = 2.0*PI*(2.0*ran2(iseed2)-1.0)
      |                                  1
Error: Type mismatch in argument ‘idum’ at (1); passed REAL(4) to INTEGER(4)
pert_sounding_module.f90:192:25:

  192 |       q(k) = mag*gaussdev(iseed1)
      |                         1
Error: Type mismatch in argument ‘idum’ at (1); passed REAL(4) to INTEGER(4)
hkershaw@cheyenne5:/glade/scratch/hkershaw/DART/Bugs/mismatch/DART/models/wrf/experiments/Radar/IC/sounding_perturbation(main)$ gfortran --version
GNU Fortran (GCC) 11.2.0
```
 I will move this to an issue, I think fix or remove this code from the repo, set as EXCLUDE  in this pull request

**Pull request merged**
