### PR TITLE
doc-fix: remove out-of-date info about inflation flavor character strings

### LINKED ISSUE #694: doc: filter_mod documentation inflation options out-of-date
https://docs.dart.ucar.edu/en/latest/assimilation_code/modules/assimilation/filter_mod.html#inflation-options
"The value for the inf_flavor is a character string"

This was reverted in https://github.com/NCAR/DART/pull/321 
inf_flavours are integers in the namelist. 

edit: also in the table

inf_flavor | character(len=32), dimension(2) | Inflation flavor [prior, posterior] see Inflation Options below.
-- | -- | --

FYI for git historians, this documentation came in in the documentation conversion from html to rst 
https://github.com/NCAR/DART/commit/00fb59c97d4cb756ed234d1e2b6c465132c8c57f
not in the pull request with the code change https://github.com/NCAR/DART/pull/154/files

### PR DESCRIPTION
**Pull request by hkershaw-brown**
## Description:

* remove out-of-date info about inflation flavor character strings
* link to inflation page rather than "program filter" which does not have any inflation info.
* added a target to the inflation section for linking 

### Fixes issue

fixes #694

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### Documentation changes needed?

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.

### Tests
Built documentation locally

## Checklist for merging

- [ ] Updated changelog entry
- [ ] Documentation updated
- [ ] Update conf.py

## Checklist for release
- [ ] Merge into main
- [ ] Create release from the main branch with appropriate tag
- [ ] Delete feature-branch

## Testing Datasets

- [ ] Dataset needed for testing available upon request
- [ ] Dataset download instructions included
- [x] No dataset needed

### CODE REVIEW

**Review by mjs2369 — COMMENTED** [review]
https://github.com/NCAR/DART/blob/d4d8d11e6f4bb1cde8bf0e9acad4e76427244614/assimilation_code/modules/assimilation/filter_mod.rst?plain=1#L96-L97

duplicate info that's in the table at line 273

**Review by mjs2369 — COMMENTED** [review]
https://github.com/NCAR/DART/blob/d4d8d11e6f4bb1cde8bf0e9acad4e76427244614/assimilation_code/modules/assimilation/filter_mod.rst?plain=1#L7-L8

Think it's more useful here to use the program names, i.e:
"Used by the filter, perfect_model_obs, and model_mod_check programs, as well as a variety of test programs."

**Review by mjs2369 — COMMENTED** [review]
https://github.com/NCAR/DART/blob/d4d8d11e6f4bb1cde8bf0e9acad4e76427244614/assimilation_code/modules/assimilation/filter_mod.rst?plain=1#L466

Don't think this is true that the only valid options are 0, 2, and 3? And in the inflation.rst doc it says otherwise:

https://github.com/NCAR/DART/blob/d4d8d11e6f4bb1cde8bf0e9acad4e76427244614/guide/inflation.rst?plain=1#L47-L57

**Comment by hkershaw-brown** [comment]
> https://github.com/NCAR/DART/blob/d4d8d11e6f4bb1cde8bf0e9acad4e76427244614/assimilation_code/modules/assimilation/filter_mod.rst?plain=1#L96-L97
> 
> duplicate info that's in the table at line 273

I think the intent of this is to stress the inflation options have a prior and posterior.  If someone does not bother to read this whole table, then this gives the "Particular options to be aware of".

**Review by mjs2369 — APPROVED** [review]
Yep, that all makes sense to me. Ready to go into main then.

**Pull request merged**
