### PR TITLE
SVN detritus cleanup

### PR DESCRIPTION
**Pull request by timhoar**
This pull request restores useful 'source' information in what I consider to be the first wave of cleanup: the programs and key modules.

### CODE REVIEW

**Comment by timhoar** [comment]
This is the first of several pull requests to remove the svn detritus. Do not close Issue 151 when this PR is merged

**Review by hkershaw-brown — CHANGES_REQUESTED** [review]
This pull request has some code changes -  the inflation flavor string changes that are in pull request #154. I think the svn detritus changes should be kept separate from any code changes.

**Comment by timhoar** [comment]
The three files that had portions of the dartlab_rtps  (PR 154) are

- assimilation_code/modules/assimilation/adaptive_inflate_mod.f90
- assimilation_code/modules/assimilation/filter_mod.f90
- assimilation_code/modules/utilities/utilities_mod.f90

and have had those unrelated updates removed.

**Review by hkershaw-brown — APPROVED** [review]
approved!

**Pull request merged**
