### PR TITLE
Remove calls to no-op routines in ensemble manager

### PR DESCRIPTION
**Pull request by ann-norcio**
## Description:
Removed the following no-op routines form ensemble manager: prepare_to_write_to_vars, prepare_to_write_to_copies, &
prepare_to_read_from_vars, prepare_to_read_from_copies, prepare_to_update_vars, &
prepare_to_update_copies 

### Fixes issue
Fixes https://github.com/NCAR/DART/issues/620

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update
- [X] Dead code removal

### Documentation changes needed?

- [ ] My change requires a change to the documentation.
  - [X] I have updated the documentation accordingly.

### Tests
Ran build_everything for branch, tested with lorenz_96 & 63 models.

## Checklist for merging

- [ ] Updated changelog entry
- [ ] Documentation updated
- [ ] Update conf.py

## Checklist for release
- [ ] Merge into main
- [ ] Create release from the main branch with appropriate tag
- [ ] Delete feature-branch

## Testing Datasets

- [ ] Dataset needed for testing available upon request
- [ ] Dataset download instructions included
- [ ] No dataset needed

### CODE REVIEW

**Review by nancycollins — APPROVED** [review]
looks good.  
they've been disabled for a while now, but i have to say for the record that when they were originally added, these checks found one place where a transpose was missing and the code was updating a stale copy of the data.  so they did serve a useful purpose back then.

**Review by hkershaw-brown — APPROVED** [review]
Approved!

@hkershaw-brown bundle with #619

**Review by hkershaw-brown — CHANGES_REQUESTED** [review]
Edit, changed my mind. 

ens_handle%valid  - remove this?

! track if copies modified last, vars modified last, both are in sync
! (and therefore both valid to be used r/o), or unknown.
integer, parameter :: VALID_UNKNOWN = -1
integer, parameter :: VALID_BOTH    =  0      ! vars & copies have same data
integer, parameter :: VALID_VARS    =  1      ! vars(:,:) modified last
integer, parameter :: VALID_COPIES  =  2      ! copies(:,:) modified last

**Comment by ann-norcio** [comment]
@hkershaw-brown commited changes to remove ens_handle%valid

**Comment by hkershaw-brown** [comment]
Nice work Ann, I'll take a look at this when I come back from PTO. Have a good weekend!

**Review by hkershaw-brown — APPROVED** [review]
Awesome work Ann! 

Code and documentation have the prepare routines gone. I checked every quickbuild.sh in DART with your build_everything tool so double plus good work. 

Approved!

Cheers,
Helen

**Pull request merged**
