### PR TITLE
Remove emojis from .md files

### PR DESCRIPTION
**Pull request by hkershaw-brown**
Fixes: https://github.com/NCAR/DART/issues/78 Removes emojis, :tada: :dart: :warning: that are not rendering properly.  

Fixes: https://github.com/NCAR/DART/issues/69 Correct description of assimilation code.

### CODE REVIEW

**Comment by timhoar** [comment]
It is disappointing that these render correctly in the markdown documents and that is not carried over when converted to html for the  GitHub Pages ...

**Comment by hkershaw-brown** [comment]
I tested the DART site locally to investigate what is happening with the github pages build ( issue https://github.com/NCAR/DART/issues/126)

You can allow emojis if you desire:

Screen Shot 2021-01-13 at 4 28 35 PM

Live version: https://hkershaw-brown.github.io/

**Comment by timhoar** [comment]
OK - *how* do you allow emojis?   Jeff Steward, Ben and I thought the emojis made the documentation less drab.
So - how did you allow the emojis?

**Comment by hkershaw-brown** [comment]
In _config.yml

Plugins:
  - jemoji

**Pull request closed without merging**
