### PR TITLE
Resolution to Issue #336 - updated nc_check

### LINKED ISSUE #336: subroutine nc_check in utilities_mod and in netcdf_utilities_mod
Replace utilities_mod::nc_check and replace with netcdf_utilities_mod::nc_check
Remove utilities_mod::nc_check from utilities module.

https://github.com/NCAR/DART/blob/90b6dcc6227faf2d82abd9c7309b21e3d78002c8/assimilation_code/modules/utilities/utilities_mod.f90#L1326-L1327

utilities_mod::nc_check in

```
models/mpas_atm/mpas_dart_obs_preprocess.f90
models/mpas_atm/resample.f90 - REMOVED
models/mpas_atm/exhaustion.f90 - REMOVED
models/mpas_atm/update_bc.f90
models/wrf_hydro/create_identity_streamflow_obs.f90

assimilation_code/programs/compute_error/compute_error.f90
observations/forward_operators/obs_def_GRACE_mod.f90

observations/obs_converters/utilities/obs_seq_utilities_mod.f90
observations/obs_converters/USGS/convert_streamflow.f90
```

Plus these lanai only model_mods:
```
models/pe2lyr/model_mod.f90
models/mpas_ocn/model_mod_check.f90
models/am2/model_mod.f90
models/forced_barot/obs/obs_mod.f90
models/NCOMMAS/model_mod.f90
models/tiegcm/model_mod.f90  - IGNORE this tiegcm is already done
models/rose/model_mod.f90
sgg model_mod has its own nc_check
models/sqg/sqg_mod.f90:SUBROUTINE nc_check(ierr,subr_name,context)
```

### PR DESCRIPTION
**Pull request by c-merchant**
## Description:
This PR replaces utilities_mod::nc_check with netcdf_utilities_mod::nc_check in:
                models/mpas_atm/mpas_dart_obs_preprocess.f90
		models/mpas_atm/update_bc.f90
		models/wrf_hydro/create_identity_streamflow_obs.f90
		assimilation_code/programs/compute_error/compute_error.f90
	        observations/forward_operators/obs_def_GRACE_mod.f90
		observations/obs_converters/utilities/obs_seq_utilities_mod.f90
		observations/obs_converters/USGS/convert_streamflow.f90
		models/pe2lyr/model_mod.f90
		models/mpas_ocn/model_mod_check.f90
		models/pe2lyr/model_mod.f90
		models/mpas_ocn/model_mod_check.f90
		models/am2/model_mod.f90
		models/forced_barot/obs/obs_mod.f90
		models/NCOMMAS/model_mod.f90
		models/rose/model_mod.f90

### Fixes issue
fixes #336 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Documentation changes needed?

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### Tests
Please describe any tests you ran to verify your changes.
I compiled DART and ran ./quickbuild.sh for Lorenz-63

## Checklist for merging

- [ ] Updated changelog entry
- [ ] Documentation updated
- [ ] Update conf.py

## Checklist for release
- [ ] Merge into main
- [ ] Create release from the main branch with appropriate tag
- [ ] Delete feature-branch

## Testing Datasets

- [ ] Dataset needed for testing available upon request
- [ ] Dataset download instructions included
- [ ] No dataset needed

### CODE REVIEW

**Comment by hkershaw-brown** [comment]
Thanks for this, I've not reviewed this closely, but one thing that is missing from the pull request is to 
remove the nc_check subroutine from utilities_mod.f90

https://github.com/c-merchant/DART/blob/c8b8d49ded09b472e5bd1cfeeeb8a9db387a40ac/assimilation_code/modules/utilities/utilities_mod.f90#L1326-L1329

**Review by mjs2369 — COMMENTED** [review]
@c-merchant @hkershaw-brown 

The following files do not actually call nc_check in the code and therefore do not need to include the line `use netcdf_utilities_mod, only : nc_check` 

models/mpas_atm/mpas_dart_obs_preprocess.f90
models/mpas_atm/update_bc.f90
observations/forward_operators/obs_def_GRACE_mod.f90
observations/obs_converters/utilities/obs_seq_utilities_mod.f90
models/forced_barot/obs/obs_mod.f90

Simply removing nc_check from the list of subroutines to use from utilities_mod is sufficient.

**Review by mjs2369 — APPROVED** [review]
This looks great @c-merchant 

I’ve compiled all relevant and Manhattan compatible models, as well as the following:
update_bc and mpas_dart_obs_preprocess for mpas_atm
filter for models/noah (which uses the obs_def_GRACE_mod.f90 file)
assimilation_code/programs/compute_error
Ameriflux obs_converter (to test changes to observations/obs_converters/utilities/obs_seq_utilities_mod.f90)
convert_streamflow in observations/obs_converters/USGS/
create_identity_streamflow_obs in models/wrf_hydro/

Approved

**Review by hkershaw-brown — APPROVED** [review]

**Comment by hkershaw-brown** [comment]
@mjs2369 we'll bundle this with #593 for the next release

**Pull request merged**
