### PR TITLE
Cam fv small fixes

### PR DESCRIPTION
**Pull request by kdraeder**
## Description:
Several small independent upgrades to cam-fv shell scripts, that have accumulated over the past months and should be committed before further work in my clone.  They address the definition of a temp directory, checking the existence of inflation files, and defining RUNDIR at the right place.

### Fixes issue
None

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Documentation changes needed?
None

### Tests
I ran the setup scripts and they set up cases correctly.

## Checklist for merging

- [x] Updated changelog entry
- [ ] Documentation updated
- [x] Update conf.py

## Checklist for release
- [ ] Merge into main
- [ ] Create release from the main branch with appropriate tag
- [ ] Delete feature-branch

## Testing Datasets

- [x ] Dataset needed for testing available upon request
         "Dataset" = all of the files needed to set up a cam-fv assimilation; too many to list here.
- [ ] Dataset download instructions included
- [ ] No dataset needed

### CODE REVIEW

**Comment by hkershaw-brown** [comment]
Hi @kdraeder These fixes look good, but you have some merges from various branches in the commits. 
Do you have half and hour or so to meet and we can fix your git history?

**Comment by kdraeder** [comment]
Do you have much lined up for your office hours?
Other times can work too.
Thanks!
Kevin

**Comment by hkershaw-brown** [comment]
not yet! swing on by this afternoon.

**Review by hkershaw-brown — APPROVED** [review]
looks good. Approved!

**Comment by hkershaw-brown** [comment]
@hkershaw-brown maybe bundle with fix for #530

**Comment by kdraeder** [comment]
Whatever's convenient for you.  None of these are holding me back.

**Pull request merged**
