### PR TITLE
MOM6 static file mask missing values

### LINKED ISSUE #685: bug: quad_utils_mod out-of-range negative for MOM6
:bug: Your bug may already be reported!
Please search on the [issue tracker](https://github.com/NCAR/DART/issues) before creating a new issue.

### Describe the bug

1. Run perturb_single_instance with MOM6 global grid TL319_t232
2. perturb a single file to get ensemble
3. error in static_init_model -> setup_interpolation -> quad_utils_mod

### Error Message  

    
     ERROR FROM:
     source : $URL$
     routine: update_reg_list
     message: unable to find right box
     message: ...  index_x may be out-of-range:            1 -2147483647         18
     0
      message: ...  index_y may be out-of-range:            1 -2147483647         18
     0
    

Looks like an integer overflow. Ran grid T62_g16 (lower res) to completion. 

https://github.com/NCAR/DART/blob/924182f29ce23f2a4e4c53aa57cc7d00fdccf374/models/utilities/quad_utils_mod.f90#L1323-L1329

### Which model(s) are you working with?
MOM6

### Version of DART      
Which version of DART are you using? 
You can find the version using `git describe --tags`  

v11.5.0-1-g4e624120f

### Have you modified the DART code?   
Yes, changed perturb_single_instance to do a perturb (rather than calling model_mod.f90 perturb routine or exiting).

https://github.com/hkershaw-brown/DART/tree/perturb-for-testing

### Build information
Please describe:  
 1. Derecho
 2. intel

### PR DESCRIPTION
**Pull request by hkershaw-brown**
## Description:

CESM3 MOM6 TL319_t232 (new workhorse grid) has missing/fill values in the static file for geolat|lon|u|v written out by CESM. 

This pull request:
* checks for fillvalue in the grid and uses the fillvalue locations as the mask to pass to quad_utils_mod.
* The grid == fillvalues are also set to a dry land lat,lon.  This is to stop set_location blowing up with lon = 1e+20.
   Note the missing value locations are not the same as the ocean_geometry 'wet' mask. 
* Forces lon to be [0-360]

Also I have set the MOM6/work/input.nml cutoff to something not giant. Not sure if 0.03 is appropriate for the ocean. 
& set the perfect_model_obs namelist init_time_days to -1 -1.

### Fixes issue

fixes #685 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Documentation changes needed?

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.

### Tests
Please describe any tests you ran to verify your changes.

Running cesm3_0_alpha03a 
/glade/derecho/scratch/hkershaw/DART/Crocodile/DART_Runs/c.TL319_t232.001
perturbed from a single instance. 
CESM: 
```
/glade/derecho/scratch/hkershaw/DART/Crocodile/CESM((cesm3_0_alpha03a))
/glade/derecho/scratch/hkershaw/DART/Crocodile/Runs/c.TL319_t232.001
../CESM/cime/scripts/create_newcase --run-unsupported --res TL319_t232 --compset C_JRA --case c.TL319_t232.001 --project P86850054
```

## Checklist for merging

- [ ] Updated changelog entry
- [ ] Documentation updated
- [ ] Update conf.py

## Checklist for release
- [ ] Merge into main
- [ ] Create release from the main branch with appropriate tag
- [ ] Delete feature-branch

## Testing Datasets

- [ ] Dataset needed for testing available upon request
- [x] Dataset download instructions included
- [ ] No dataset needed

### CODE REVIEW

**Comment by hkershaw-brown** [comment]
note added this fix to https://github.com/NCAR/DART/tree/mom6-scripting
which has the mom6 assimilate.sh that Enrico is kicking the tires on.

**Review by mjs2369 — COMMENTED** [review]
[https://github.com/NCAR/DART/blob/f04bf424bcb17db187666ba9af04c3629cd67a24/models/MOM6/model_mod.f90#L621-L624](https://github.com/NCAR/DART/blob/f04bf424bcb17db187666ba9af04c3629cd67a24/models/MOM6/model_mod.f90#L621-L624)

Why don't we need to repeat this process done in the lines above for geolon_u and geolon_v and have a separate mask array for each? These mask arrays, for example, `mask_geolon_u` would be passed into their respective calls to set_quad_coords. Example:
`call set_quad_coords(interp_u_grid, geolon_u, geolat_u, mask_geolon_u)`

Is this because the missing values are always going to be in the same place for gelon, geolon_u, and geolon_v? And therefore the mask array would be simply be duplicated for geolon_u and geolon_v?

**Comment by mjs2369** [comment]
> There are in the same place for the case , but you're correct there's no guarantee that that will always be the case. I'll add a mask for each

Should we have a separate array for the fillval as well or is that not needed?
fillval, fillval_u, fillval_v

**Comment by hkershaw-brown** [comment]
> > There are in the same place for the case , but you're correct there's no guarantee that that will always be the case. I'll add a mask for each
> 
> Should we have a separate array for the fillval as well or is that not needed? fillval, fillval_u, fillval_v

Do you mean move the `where (geolon_u == fillval) geolon_u = 72.51` in case the fill values are different for each variable? Yeah probably wise.

```
call nc_get_attribute_from_variable(ncid, 'geolon_u', '_FillValue', fillval)
where (geolon_u == fillval) mask_u = .true.  
where (geolon_u == fillval) geolon_u = 72.51`
```

**Comment by mjs2369** [comment]
> Do you mean move the `where (geolon_u == fillval) geolon_u = 72.51` in case the fill values are different for each variable? Yeah probably wise.
> 
> ```
> call nc_get_attribute_from_variable(ncid, 'geolon_u', '_FillValue', fillval)
> where (geolon_u == fillval) mask_u = .true.  
> where (geolon_u == fillval) geolon_u = 72.51`
> ```

Yep that's exactly it

And do `where (geolat_u == fillval) geolat_u = 42.56` as well before the next call to nc_get_attribute_from_variable

So the full thing would be
```
call nc_get_attribute_from_variable(ncid, 'geolon_u', '_FillValue', fillval)
where (geolon_u == fillval) 
  mask_u = .true.  
  geolon_u = 72.51
where (geolat_u == fillval) geolat_u = 42.56
```

**Review by mjs2369 — APPROVED** [review]
Everything looks good. Nice fix Helen

I ended up testing with the case you had in /glade/derecho/scratch/hkershaw/DART/Crocodile/DART_Runs/c.TL319_t232.001

I was getting the error message shown in the corresponding issue when running filter on the main branch, but I was able to run filter successfully on the mom6-missing-grid branch with all the latest commits.

**Pull request merged**
